CREATE DATABASE IF NOT EXISTS larpets;
CREATE TABLE IF NOT EXISTS tutores (
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	senha VARCHAR(255) NOT NULL,
    telefone VARCHAR(255) NOT NULL
);
